### PR TITLE
Skill choice contains multiple languages

### PR DESCRIPTION
**Pull request by epaminond**

### CODE REVIEW

**Review by slvnperron — CHANGES_REQUESTED** [review]
@epaminond We should actually use the `Content Picker` for all text areas in all skills

**Comment by epaminond** [comment]
@slvnperron , do you mean for choice-options either?

**Comment by slvnperron** [comment]
@epaminond This will suck very much for choices (having to create content elements for each) but I think it's the right solution. Content creation is something we need to make much easier and better from a UX point of view.

An idea is that we could have a `<ContentPicker defaultContentType="text" enablePickingExisting={true} enableCreateNew={true} allowChangeContentType={false} />`, which would automatically pick `text` as the content type. From there we will need to work on improving the creation of new text content types (making it a single click/shortcut away).

**Comment by epaminond** [comment]
Got it - OK, will change this.

**Pull request closed without merging**
